version: '3'
services:
  app:
    image: wordpress:5-apache
    depends_on:
      - mysql
    env_file: ./.app.env
    ports:
    - "8080:80"
    volumes:
      - "appdata:/var/www/html"
  mysql:
    image: mysql:5.7
    expose: [3306]
    env_file: ./.db.env
    volumes:
      - "dbdata:/var/lib/mysql"

volumes:
  appdata:
  dbdata:
